### ISSUE TITLE
Crash with java version 14

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Thuts-Mods/ThutCore#1]
https://gist.github.com/P3rf3ctXZer0/79f23c8bdc79b41a93dbaf75f21b4366

**Comment by P3rf3ctXZer0** [comment]
![bHd2Qt9](https://user-images.githubusercontent.com/10351221/81848059-23c4a680-951a-11ea-933e-dbc5389f90e8.png)

**Comment by Thutmose** [comment]
fixed in 7.2.1 for thutcore (also in current pokecube)
