### ISSUE TITLE
Failed to load ThutCore on Apex Hosting Server

### ISSUE THREAD

**Issue by trexrazor123** [Thuts-Mods/ThutCore#8]
I am trying to get the better boats mod and thutcore is required for it. I have the most recent versions of each mod and forge installed and I still am getting an error on startup, stopping the server. Here is the crash log. Any help would be much appreciated! Thank you!

-- Head --
10.01 16:23:02 [Server] INFO Thread: main
10.01 16:23:02 [Server] INFO Stacktrace:
10.01 16:23:02 [Server] INFO at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
10.01 16:23:02 [Server] INFO -- MOD thutcrafts --
10.01 16:23:02 [Server] INFO Details:
10.01 16:23:02 [Server] INFO Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/server/permission/nodes/PermissionNode
10.01 16:23:02 [Server] INFO at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-5.0.3.jar%232!:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-5.0.3.jar%232!:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[javafmllanguage-1.18.1-39.0.0.jar%2362!:?] {}
10.01 16:23:02 [Server] INFO at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[javafmllanguage-1.18.1-39.0.0.jar%2362!:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[javafmllanguage-1.18.1-39.0.0.jar%2362!:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.0.jar%2361!:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
10.01 16:23:02 [Server] INFO Mod File: thutcore-1.18.1-8.6.3 (2).jar
10.01 16:23:02 [Server] INFO Failure message: Thut Crafts (thutcrafts) has failed to load correctly
10.01 16:23:02 [Server] INFO java.lang.NoClassDefFoundError: net/minecraftforge/server/permission/nodes/PermissionNode
10.01 16:23:02 [Server] INFO Mod Version: 8.6.3
10.01 16:23:02 [Server] INFO Mod Issue URL: https://github.com/Thutmose/Thut/issues
10.01 16:23:02 [Server] INFO Exception message: java.lang.ClassNotFoundException: net.minecraftforge.server.permission.nodes.PermissionNode
10.01 16:23:02 [Server] INFO Stacktrace:
10.01 16:23:02 [Server] INFO at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
10.01 16:23:02 [Server] INFO at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.54.jar:?] {}
10.01 16:23:02 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
10.01 16:23:02 [Server] INFO at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.54.jar:?] {}
10.01 16:23:02 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-5.0.3.jar%232!:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-5.0.3.jar%232!:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[javafmllanguage-1.18.1-39.0.0.jar%2362!:?] {}
10.01 16:23:02 [Server] INFO at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[javafmllanguage-1.18.1-39.0.0.jar%2362!:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[javafmllanguage-1.18.1-39.0.0.jar%2362!:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.0.jar%2361!:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
10.01 16:23:02 [Server] INFO -- MOD thutcore --
10.01 16:23:02 [Server] INFO Details:
10.01 16:23:02 [Server] INFO Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/server/permission/nodes/PermissionNode
10.01 16:23:02 [Server] INFO at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-5.0.3.jar%232!:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-5.0.3.jar%232!:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[javafmllanguage-1.18.1-39.0.0.jar%2362!:?] {}
10.01 16:23:02 [Server] INFO at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[javafmllanguage-1.18.1-39.0.0.jar%2362!:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[javafmllanguage-1.18.1-39.0.0.jar%2362!:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.0.jar%2361!:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
10.01 16:23:02 [Server] INFO Mod File: thutcore-1.18.1-8.6.3 (2).jar
10.01 16:23:02 [Server] INFO Failure message: Thut Core (thutcore) has failed to load correctly
10.01 16:23:02 [Server] INFO java.lang.NoClassDefFoundError: net/minecraftforge/server/permission/nodes/PermissionNode
10.01 16:23:02 [Server] INFO Mod Version: 8.6.3
10.01 16:23:02 [Server] INFO Mod Issue URL: https://github.com/Thutmose/Thut/issues
10.01 16:23:02 [Server] INFO Exception message: java.lang.ClassNotFoundException: net.minecraftforge.server.permission.nodes.PermissionNode
10.01 16:23:02 [Server] INFO Stacktrace:
10.01 16:23:02 [Server] INFO at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
10.01 16:23:02 [Server] INFO at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.54.jar:?] {}
10.01 16:23:02 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
10.01 16:23:02 [Server] INFO at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.54.jar:?] {}
10.01 16:23:02 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {}
10.01 16:23:02 [Server] INFO at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {}
10.01 16:23:02 [Server] INFO at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-5.0.3.jar%232!:?] {}
10.01 16:23:03 [Multicraft] Server shut down (starting)
10.01 16:23:03 [Multicraft] Restarting crashed server in 300 seconds
10.01 16:23:03 [Multicraft] Server stopped

**Comment by Thutmose** [comment]
update forge
